# Generated by Django 4.2.3 on 2023-08-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='hello', upload_to='imgs'),
            preserve_default=False,
        ),
    ]
